name: Deploy Action
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: github-pages
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Deploy
              run: |
                  npm ci --legacy-peer-deps
                  git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
                  npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CI: False
                  REACT_APP_OPENWEATHERMAP_API_KEY: ${{ secrets.REACT_APP_OPENWEATHERMAP_API_KEY }}
                  REACT_APP_NEWS_API_KEY: ${{ secrets.REACT_APP_NEWS_API_KEY }}
